#!/usr/bin/python3
import sys

def factorize_number(number):
    factors = []
    for i in range(2, number//2 + 1):
        if number % i == 0:
            factors.append((i, number // i))
    return factors

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

input_file = sys.argv[1]

try:
    with open(input_file, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorize_number(number)
            for factor in factors:
                print(f"{number}={factor[0]}*{factor[1]}")
except FileNotFoundError:
    print(f"Error: File '{input_file}' not found.")
    sys.exit(1)
except ValueError:
    print(f"Error: Invalid input in file '{input_file}'.")
    sys.exit(1)
